### ISSUE TITLE
LSTM model for HLS generation

### ISSUE THREAD

**Issue by samifry** [fastmachinelearning/hls4ml#412]
Hi!

I've tried the demo of HLS generation for the LSTM model example from : https://github.com/fastmachinelearning/hls4ml/tree/recursive2 . It works, but I need to know if the solution is supported for RTL generation and for FPGA implementation. I need to do that with a current LSTM network with a large set of data. Maybe there is other issues to do that ? I also want to use this repository : https://github.com/richarao/hls4ml/tree/keras-lstm

The demo doesn't work for me, probably because I forgot to do something. This error appear after calling keras-to-hls function like that:
```
#load yml file
with open('keras-config.yml') as f:
    yamlConfig = yaml.load(f, Loader=yaml.FullLoader)
if __name__ == "__main__":
    keras_to_hls(yamlConfig)
```
The following error appear:
```
Traceback (most recent call last):
  File "../../hls4ml/converters/keras_to_hls.py", line 554, in <module>
    keras_to_hls(yamlConfig)
  File "../../hls4ml/converters/keras_to_hls.py", line 545, in keras_to_hls
    hls_model = HLSModel(yamlConfig, reader, layer_list, input_layers, output_layers)
  File "/home/samif/.local/lib/python3.8/site-packages/hls4ml/model/hls_model.py", line 264, in __init__
    self._make_graph(layer_list)
  File "/home/samif/.local/lib/python3.8/site-packages/hls4ml/model/hls_model.py", line 279, in _make_graph
    self.graph[name] = self.make_node(kind, name, layer, inputs, outputs)
  File "/home/samif/.local/lib/python3.8/site-packages/hls4ml/model/hls_model.py", line 285, in make_node
    node = layer_map[kind](self, name, attributes, inputs, outputs)
KeyError: 'LSTM'
```
I'll be very grateful if someone can help me to fix this 

Thanks in advance!
Sami

**Comment by TitechTraj** [comment]
Hi Sami,
I am trying to generate LSTM (and later GRU) and used the recursive2 branch too. Did you manage to synthesize the model with Vivado HLS?
The first step of converting the model ( python keras-to-hls.py -c keras-config.yml ) seems to work, but when I run vivado_hls, I end up on some errors:
`hls4ml_recursive2/nnet_utils/nnet_recursive.h:434:93: error: use of overloaded operator '<<' is ambiguous (with operand types 'ostream' (aka 'basic_ostream<char>') and 'ap_fixed<18, 8, 5, 3, 0>')`
and
`hls4ml_recursive2/nnet_utils/nnet_recursive.h:435:93: error: use of overloaded operator '<<' is ambiguous (with operand types 'ostream' (aka 'basic_ostream<char>') and 'ap_fixed<18, 8, 5, 3, 0>')`

I am using Vivado 2019.2 and since this branch is old, I am wondering if it is a version issue. Did you run into a similar problem?

Thanks for sharing

**Comment by TitechTraj** [comment]
By the way, I tried to run the code from the other repository ( https://github.com/richarao/hls4ml/tree/keras-lstm) and used the following python script:
```python
import yaml
import hls4ml

#load yml file
with open('keras-config.yml') as f:
    yamlConfig = yaml.load(f, Loader=yaml.FullLoader)

if __name__ == "__main__":
    model=hls4ml.converters.keras_to_hls(yamlConfig)
```
It worked for me and had the output:
```
Interpreting Model
Topology:
Layer name: input_1, layer type: InputLayer, current shape: [[None, 20, 6]]
Layer name: lstm_lstm, layer type: LSTM, current shape: [[None, 20, 6]]
Layer name: rnn_densef, layer type: Dense, current shape: [[None, 120]]
Creating HLS model
```
I am wondering if your problem is with using a different hls4ml branch that does not have LSTM defined. Did you try to install python setup.py install from the root of https://github.com/richarao/hls4ml/tree/keras-lstm ?

**Comment by TitechTraj** [comment]
Update on my HLS synthesis issue. It was just an incompatible version. Both projects were generated using Vivado HLS 2018.2 successfully.

**Comment by samifry** [comment]
Hi @TitechTraj ,

Thank you for your return.

I also fixed my problem, I had the official version of hls4ml installed and this provided some conflicts. If ever, I've used this branch https://github.com/chaitanyaPaikara/hls4ml/tree/keras-RNN for LSTM conversion and I can confirm that the results are satisfactory in the final hardware level. This is just a more updated version than this https://github.com/richarao/hls4ml/tree/keras-lstm

**Comment by TitechTraj** [comment]
Oh great, thanks for sharing. I haven't implemented the hardware on the board but good to know that the new branch has more updated code. I will try it tomorrow.

**Comment by ntsakoulis** [comment]
Is it possible to generate HLS project with GRU or LSTM layers

**Comment by TrajM** [comment]
If your network is not too large, I think it works. For my design I have 2 GRU cells with 120 hidden units and an input larger than 512, it didn't fit and I gave up, you would need a lot of manual HLS optimizations (for loop unrolling and array partitions).
I updated the RNN branch with hls4ml v0.6.0 to be able to use the pynq accelerator template (as explained in the official tutorials)
Give it a try and see if it works for you:

https://github.com/TitechTraj/hls4ml/tree/keras-RNN

**Comment by TitechTraj** [comment]
If your network is not too large, I think it works. For my design I have 2 GRU cells with 120 hidden units and an input larger than 512, it didn't fit and I gave up, you would need a lot of manual HLS optimizations (for loop unrolling and array partitions).
I updated the RNN branch with hls4ml v0.6.0 to be able to use the pynq accelerator template (as explained in the official tutorials)
Give it a try and see if it works for you:

https://github.com/TitechTraj/hls4ml/tree/keras-RNN
